### ISSUE TITLE
selenium起動時のメモリ不足によるエラー

### ISSUE THREAD

**Issue by haruspring-jokt** [haruspring-jokt/tenkibot#4]
## 概要

FOLIOの情報を取得する処理の実行時、メモリ不足？でエラーになる。たぶんseleniumを終了していないだと思われる。

### stackoverflow

https://stackoverflow.com/questions/32328060/selenium-headless-browser-webdriver-errno-104-connection-reset-by-peer

### エラー内容

出先なので後で

**Comment by haruspring-jokt** [comment]
エラーログは以下:

[post_folio_summary] I had a problem handling "folio"

```
Traceback (most recent call last):
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
   chunked=chunked)
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
   six.raise_from(e, None)
 File "<string>", line 2, in raise_from
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
   httplib_response = conn.getresponse()
 File "/app/.heroku/python/lib/python3.7/http/client.py", line 1321, in getresponse
   response.begin()
 File "/app/.heroku/python/lib/python3.7/http/client.py", line 296, in begin
   version, status, reason = self._read_status()
 File "/app/.heroku/python/lib/python3.7/http/client.py", line 257, in _read_status
   line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
 File "/app/.heroku/python/lib/python3.7/socket.py", line 589, in readinto
   return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/app/.heroku/python/lib/python3.7/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
   func(Message(self._client, msg), *args)
 File "/app/template/money_template.py", line 30, in post_folio_summary
   folio_service.send_folio_sammary(channel)
 File "/app/service/folio_service.py", line 9, in send_folio_sammary
   sammary = folio_repository.fetch_sammary()
 File "/app/repository/folio_repository.py", line 22, in fetch_sammary
   driver = setup_webdriver()
 File "/app/repository/folio_repository.py", line 104, in setup_webdriver
   options=options, executable_path=CHROME_DRIVER_PATH)
 File "/app/.heroku/python/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
   desired_capabilities=desired_capabilities)
 File "/app/.heroku/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
   self.start_session(capabilities, browser_profile)
 File "/app/.heroku/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
   response = self.execute(Command.NEW_SESSION, parameters)
 File "/app/.heroku/python/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
   response = self.command_executor.execute(driver_command, params)
 File "/app/.heroku/python/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
   return self._request(command_info[0], url, body=data)
 File "/app/.heroku/python/lib/python3.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
   resp = self._conn.request(method, url, body=body, headers=headers)
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/request.py", line 72, in request
   **urlopen_kw)
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/request.py", line 150, in request_encode_body
   return self.urlopen(method, url, **extra_kw)
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/poolmanager.py", line 323, in urlopen
   response = conn.urlopen(method, u.request_uri, **kw)
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
   _stacktrace=sys.exc_info()[2])
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
   raise six.reraise(type(error), error, _stacktrace)
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
   raise value.with_traceback(tb)
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
   chunked=chunked)
File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
   six.raise_from(e, None)
 File "<string>", line 2, in raise_from
 File "/app/.heroku/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
   httplib_response = conn.getresponse()
 File "/app/.heroku/python/lib/python3.7/http/client.py", line 1321, in getresponse
   response.begin()
 File "/app/.heroku/python/lib/python3.7/http/client.py", line 296, in begin
   version, status, reason = self._read_status()
 File "/app/.heroku/python/lib/python3.7/http/client.py", line 257, in _read_status
   line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
 File "/app/.heroku/python/lib/python3.7/socket.py", line 589, in readinto
   return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

```

**Comment by haruspring-jokt** [comment]
seleniumのバージョンを`3.8.0`に指定し、安定動作しています。

```
selenium==3.8.0
```
